#!/bin/bash
set -e
set -x

echo Note that things are picked up from .ssh/config now
SHELL=/bin/sh PWD=/ ./sidecore -9p=false -nfs=true   k10.4
exit 0
SHELL=/bbin/elvish PWD=/ ./sidecore -container amd64-ubuntu@latest.cpio -key /home/rminnich/.ssh/cpu_rsa localhost $*
exit 0
SHELL=/bbin/elvish PWD=/ ./sidecore -container  ~/go/src/github.com/u-root/cpu/client/data/a.cpio -key /home/rminnich/.ssh/cpu_rsa localhost $*
exit 0
